language: php
php:
  - 7.3
  - 7.4
  - 8.0
env: PHPV=0
install: |
  composer install
script: |
  composer run-script test -- --colors --coverage-text
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
